ROUNDABOUT v0.1.3

diff --git a/etc/hotplug.d/iface/60-roundabout b/etc/hotplug.d/iface/60-roundabout
--- a/etc/hotplug.d/iface/60-roundabout
+++ b/etc/hotplug.d/iface/60-roundabout
@@ -3,7 +3,7 @@
 #                                                                              #
 #                              ROUNDABOUT by KB19                              #
 #                            ----------------------                            #
-#                             v0.1.2 -- 2018/04/20                             #
+#                             v0.1.3 -- 2018/04/21                             #
 #                                                                              #
 # Successor of OWRHS (routing helper script). Now with UCI support.            #
 # Designed for OpenWrt 15.05 or newer, tested with version 15.05.1!            #
@@ -50,6 +50,7 @@
 #   iface.routing_table     = <...>  ID or name, see: /etc/iproute2/rt_tables  #
 #   iface.name              = <...>  Use another name for OpenDNS and table.   #
 #   iface.hostname          = <...>  Use another hostname for OpenDNS.         #
+#   iface.route             = <...>  Custom routes for this interface.         #
 #                                                                              #
 # Warning: All leds will be switched off at ifdown or default route loss!      #
 # It's a bit tricky to get the desired results, maybe there are bugs too.      #
@@ -221,6 +222,20 @@ disable_leds()
 	done
 }
 
+# Get IP version of address.
+# Really bad implementation!
+get_ipversion()
+{
+	local __;
+
+	if [ "$1" != "${1#*[0-9].[0-9]}" ]; then __=4
+	elif [ "$1" != "${1#*:}" ]; then __=6
+	else return 1; fi
+
+	if [ -z "$2" ]; then echo "$__"
+	else get_var "__" "$2"; fi
+}
+
 config_load "$SCR" || exit 1
 log "Main configuration loaded into memory." "debug"
 log "VARDUMP: INTERFACE=${INTERFACE}; ACTION=${ACTION}; DEVICE=${DEVICE}" "debug"
@@ -250,6 +265,7 @@ config_get      restart_service_default  "$cfg_global"  restart_service
 config_get      restart_network_default  "$cfg_global"  restart_network
 config_get      restart_service_extended "$INTERFACE"   restart_service
 config_get      restart_network_extended "$INTERFACE"   restart_network
+config_get      routes                   "$INTERFACE"   route
 
 # All other UCI elements...
 config_get_bool odns_enable              "$cfg_opendns" enable           "0"
@@ -278,6 +294,9 @@ log "VARDUMP: restart_services=${restart_services} (${restart_service_default} $
 
 if [ "$ACTION" = "ifup" ]
 then
+	network_get_gateway  "gw4" "$INTERFACE"
+	network_get_gateway6 "gw6" "$INTERFACE"
+
 	if [ "$source_routing" = "1" -o "$source_routing" -eq 2 ]
 	then
 		prefix4="32"
@@ -289,9 +308,6 @@ then
 		ip4=`ip -o -4 addr show "$DEVICE" scope global | awk '{ sub(/\/.*$/,"",$4); print $4 "/'"$prefix4"'" }'`
 		ip6=`ip -o -6 addr show "$DEVICE" scope global | awk '{ sub(/\/.*$/,"",$4); print $4 "/'"$prefix6"'" }' | grep -v '^f' | grep -v '\.'`
 		if [ "$ip6prefix" != "" ]; then ip6="$ip6 $ip6prefix"; fi
-
-		network_get_gateway "gw4" "$INTERFACE"
-		network_get_gateway6 "gw6" "$INTERFACE"
 
 		if [ "$ip4" = "" -o "$gw4" = "" ]
 		then
@@ -359,6 +375,37 @@ then
 
 	if [ "$restart_networks" -eq 1 -o "$restart_networks" -eq 2 ]; then
 	restart_networks "$restart_network_default $restart_network_extended"; fi
+
+	if [ ! -z "$routes" ]
+	then
+		__network_ifstatus "metric" "$INTERFACE" ".metric"
+		metric="${metric:-0}"
+
+		for to in $routes
+		do
+			realto=`echo "$to" | cut -d '#' -f 1`
+			realmetric=`echo "$to" | cut -d '#' -f 2 -s`
+			if [ -z "$realmetric" ]; then realmetric=$metric; fi
+
+			if get_ipversion "$to" "ipv"
+			then
+				if [ "$ipv" -eq 4 ]; then realgw=$gw4
+				elif [ "$ipv" -eq 6 ]; then realgw=$gw6
+				fi
+			else
+				log "Invalid route destination: $to" "warning"
+				continue
+			fi
+
+			if [ ! -z "$realgw" ]
+			then
+				ip route add "$realto" via "$realgw" dev "$DEVICE" metric "$realmetric"; status=$?
+				if [ "$status" -eq 0 ]; then log "New route: $realto via $realgw dev $DEVICE metric $realmetric" "info"
+				elif [ "$status" -ne 1 ]; then log "Invalid route: $realto via $realgw dev $DEVICE metric $realmetric" "warning"
+				fi
+			fi
+		done
+	fi
 
 elif [ "$ACTION" = "ifdown" ]
 then
